### ISSUE TITLE
EnergyRM org on GitHub

### ISSUE THREAD

**Issue by cainlevy** [EnergyRM/deltamtrsvs-api-python-client#7]
Hi Eric -- I've just started with EnergyRM and would love to chat about using the GitHub org. Send me a message at `$first.$last@en-rm.com` and I'll be happy to catch up and verify anything.

**Comment by eayoungs** [comment]
Hi, Lance. I'm happy to chat. I haven't been involved with EnergyRM for a while now but I'd love to hear about any new developments.
